server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  cache:
    redis:
      #使用前缀
      use-key-prefix: true
      #redis过期时间
      time-to-live: 60s
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
      #schema: classpath:/sql/schema.sql
  type-aliases-package: com.movie.api.model.entity